list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})

set(KAMINPAR_BUILD_DISTRIBUTED OFF)
set(KAMINPAR_BUILD_WITH_SPARSEHASH ON)
set(KAMINPAR_BUILD_WITH_MTKAHYPAR OFF)
set(KAMINPAR_BUILD_WITH_KASSERT ON)

set(KAMINPAR_DOWNLOAD_MTKAHYPAR OFF)
set(KAMINPAR_DOWNLOAD_KASSERT ON)
set(KAMINPAR_DOWNLOAD_KAGEN OFF)

include(CMakeFindDependencyMacro)
find_dependency(TBB REQUIRED)

if(KAMINPAR_BUILD_WITH_SPARSEHASH)
  find_dependency(Sparsehash REQUIRED)
endif()

if(KAMINPAR_BUILD_WITH_MTKAHYPAR AND NOT KAMINPAR_DOWNLOAD_MTKAHYPAR)
  find_dependency(mtkahypar REQUIRED)
endif()

if(KAMINPAR_BUILD_WITH_KASSERT AND NOT KAMINPAR_DOWNLOAD_KASSERT)
  find_dependency(kassert REQUIRED)
endif()

if(KAMINPAR_BUILD_DISTRIBUTED)
  find_dependency(MPI REQUIRED)

  if(NOT KAMINPAR_DOWNLOAD_KAGEN)
    find_dependency(kagen REQUIRED)
  endif()
endif()

include("${CMAKE_CURRENT_LIST_DIR}/KaMinParTargets.cmake")
