if(EXISTS "/Users/daniel/.codex/worktrees/d883/KaMinPar/tests/test_common_compact_static_array[1]_tests.cmake")
  include("/Users/daniel/.codex/worktrees/d883/KaMinPar/tests/test_common_compact_static_array[1]_tests.cmake")
else()
  add_test(test_common_compact_static_array_NOT_BUILT test_common_compact_static_array_NOT_BUILT)
endif()
