name: Benchmark 

on: [ push, pull_request ]

jobs:
  kaminpar_tests:
    runs-on: self-hosted
    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release 
        env:
         CC: gcc-10
         CXX: g++-10

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Release --parallel 4

      - name: Run benchmark script
        working-directory: ${{github.workspace}}/misc/ci/benchmark
        run: ./benchmark.sh
        env:
          BENCHMARK_DIR: /kaminpar_ci
          KAMINPAR_CURRENT: ${{github.workspace}}/build/apps/KaMinPar
          KAMINPAR_STABLE: /home/docker/kaminpar_esa21/build/apps/KaMinPar

