name: clang-format Check

on: [ push, pull_request ]

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest 
    steps:
    - name: Checkout HEAD
      uses: actions/checkout@v2

    - name: Check formatting
      uses: jidicula/clang-format-action@v4.6.1
      with:
        clang-format-version: '13'
        exclude-regex: 'external_tools/'

