name: Example Builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build_simple_example:
    name: Build simple example
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: ["gcc", "clang"]
    steps:
      - name: Checkout KaMinPar
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Modify CMakeLists.txt for PR builds
        if: github.event_name == 'pull_request'
        run: |
          REPO_NAME="${{ github.event.pull_request.head.repo.full_name }}"
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          if [[ ! "$REPO_NAME" =~ ^[a-zA-Z0-9._/-]+$ ]]; then
              echo "Invalid repository name: $REPO_NAME" >&2
            exit 1
          fi
          if [[ ! "$BRANCH_NAME" =~ ^[a-zA-Z0-9._/-]+$ ]]; then
            echo "Invalid branch name: $BRANCH_NAME" >&2
            exit 1
          fi
          sed -i.bak "s|GIT_REPOSITORY .*|GIT_REPOSITORY https://github.com/${REPO_NAME}.git|" examples/simple/CMakeLists.txt
          sed -i.bak "s|GIT_TAG .*|GIT_TAG ${BRANCH_NAME}|" examples/simple/CMakeLists.txt

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build libtbb-dev libhwloc-dev libsparsehash-dev

      - name: Configure
        working-directory: ${{github.workspace}}/examples/simple
        run: cmake --preset=ci-${{matrix.compiler}}-linux

      - name: Build
        working-directory: ${{github.workspace}}/examples/simple
        run: cmake --build --preset=ci-${{matrix.compiler}}-linux
