name: KaMinPar CI

on: [ push, pull_request ]

jobs:
  kaminpar_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get install gcc-10 g++-10 libtbb-dev libhwloc-dev mpi libopenmpi-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DKAMINPAR_ENABLE_HEAVY_ASSERTIONS=On -DKAMINPAR_ENABLE_LIGHT_ASSERTIONS=On -DKAMINPAR_BUILD_TESTS=On
        env:
         CC: gcc-10
         CXX: g++-10

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config Debug

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: |
          ctest -C Debug
          cat ${{github.workspace}}/build/Testing/Temporary/LastTest.log