name: Nix Package Build Tester

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-package:
    name: Build Packages for ${{ matrix.platform[0] }} target
    strategy:
      matrix:
        platform:
          - ["x86_64-linux", ubuntu-24.04]
          - ["aarch64-linux", ubuntu-24.04-arm]
          - ["aarch64-darwin", macos-15]
      fail-fast: false

    runs-on: ${{ matrix.platform[1] }}
    steps:
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@786fff0690178f1234e4e1fe9b536e94f5433196 # v20

      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@565684385bcd71bad329742eefe8d12f2e765b39 # v13

      - name: Checkout KaMinPar
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Build KaMinPar
        run: nix build --print-build-logs .#kaminpar

      - name: Build Python bindings for KaMinPar
        run: nix build --print-build-logs .#kaminpar-python

      - name: Build NetworKit bindings for KaMinPar
        if: ${{ matrix.platform[0] != 'aarch64-darwin' }}
        run: nix build --print-build-logs .#kaminpar-networkit
