name: Wheel builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build_python_wheels:
    name: Build KaMinPar Python wheel for ${{ matrix.python }}  with 64-bit IDs set to ${{ matrix.bit64 }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["cp311", "cp312", "cp313", "cp313t", "pp310", "pp311"]
        bit64: ["Off", "On"]
    steps:
    - name: Checkout KaMinPar
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Build wheels
      uses: pypa/cibuildwheel@6cccd09a31908ffd175b012fb8bf4e1dbda3bc6c # v2.23.0
      env:
        CIBW_BUILD: ${{ matrix.python }}-manylinux_x86_64
        CIBW_ENVIRONMENT: SKBUILD_CMAKE_DEFINE="KAMINPAR_PYTHON_INSTALL_TBB=On;KAMINPAR_PYTHON_64BIT=${{ matrix.bit64 }}"
        CIBW_FREE_THREADED_SUPPORT: True
      with:
        package-dir: bindings/python

  build_networkit_wheels:
    name: Build KaMinPar NetworKit wheel for ${{ matrix.python }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["cp311", "cp312"]
    steps:
    - name: Checkout KaMinPar
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Build wheels
      uses: pypa/cibuildwheel@6cccd09a31908ffd175b012fb8bf4e1dbda3bc6c # v2.23.0
      env:
        CIBW_BUILD: ${{ matrix.python }}-manylinux_x86_64
      with:
        package-dir: bindings/networkit

  build_python_sdist:
    name: Build KaMinPar Python source distribution
    runs-on: ubuntu-latest
    steps:
    - name: Checkout KaMinPar
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: '3.12'

    - name: Build source distribution
      run: |
        python -m pip install build
        python -m build --sdist bindings/python/

  build_networkit_sdist:
    name: Build KaMinPar NetworKit source distribution
    runs-on: ubuntu-latest
    steps:
    - name: Checkout KaMinPar
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: '3.12'

    - name: Build source distribution
      run: |
        python -m pip install build
        python -m build --sdist bindings/networkit/
