name: Wheel builder

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build_python_wheels:
    name: Build KaMinPar Python wheel for ${{ matrix.python }}

    strategy:
      matrix:
        python: ["cp39", "cp310", "cp311", "cp312", "cp313", "cp313t", "pp39", "pp310", "pp311"]
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
    - name: Checkout KaMinPar
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Build wheels
      uses: pypa/cibuildwheel@6cccd09a31908ffd175b012fb8bf4e1dbda3bc6c # v2.23.0
      env:
        CIBW_BUILD: ${{ matrix.python }}-manylinux_x86_64
        CIBW_ENVIRONMENT: SKBUILD_CMAKE_DEFINE="KAMINPAR_PYTHON_INSTALL_TBB=On"
        CIBW_FREE_THREADED_SUPPORT: True
      with:
        package-dir: bindings/python
        output-dir: bindings/python/dist

    - name: Store wheels
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: kaminpar-python-wheel-${{ matrix.python }}
        path: bindings/python/dist/
        if-no-files-found: error

  build_networkit_wheels:
    name: Build KaMinPar NetworKit wheel for ${{ matrix.python }}

    strategy:
      matrix:
        python: ["cp310", "cp311", "cp312", "cp313"]
      fail-fast: false

    runs-on: ubuntu-latest
    steps:
    - name: Checkout KaMinPar
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Build wheels
      uses: pypa/cibuildwheel@6cccd09a31908ffd175b012fb8bf4e1dbda3bc6c # v2.23.0
      env:
        CIBW_BUILD: ${{ matrix.python }}-manylinux_x86_64
      with:
        package-dir: bindings/networkit
        output-dir: bindings/networkit/dist

    - name: Store wheels
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: kaminpar-networkit-wheel-${{ matrix.python }}
        path: bindings/networkit/dist/
        if-no-files-found: error

  build_python_sdist:
    name: Build KaMinPar Python source distribution
    runs-on: ubuntu-latest
    steps:
    - name: Checkout KaMinPar
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: '3.13'

    - name: Build source distribution
      run: |
        python -m pip install build
        python -m build --sdist bindings/python/

    - name: Store sdist
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: kaminpar-python-sdist
        path: bindings/python/dist/
        if-no-files-found: error

  build_networkit_sdist:
    name: Build KaMinPar NetworKit source distribution
    runs-on: ubuntu-latest
    steps:
    - name: Checkout KaMinPar
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Set up Python
      uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
      with:
        python-version: '3.13'

    - name: Build source distribution
      run: |
        python -m pip install build
        python -m build --sdist bindings/networkit/

    - name: Store sdist
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: kaminpar-networkit-sdist
        path: bindings/networkit/dist/
        if-no-files-found: error
